Kodoyosa\DashboardBundle\Entity\General:
    type: entity
    table: kdb_general
    repositoryClass: Kodoyosa\DashboardBundle\Repository\GeneralRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        active:
            type: boolean
    lifecycleCallbacks: {  }
