main_front_itemmenu:
    resource: "@KodoyosaDashboardBundle/Resources/config/routing/itemmenu.yml"
    prefix:   /itemmenu

main_front_sectionmenu:
    resource: "@KodoyosaDashboardBundle/Resources/config/routing/sectionmenu.yml"
    prefix:   /sectionmenu

main_front_general:
    resource: "@KodoyosaDashboardBundle/Resources/config/routing/general.yml"
    prefix:   /general

kodo_dashboard_homepage:
    path:     /
    defaults: { _controller: KodoyosaDashboardBundle:Default:index }
