services:
    kodoyosa_dashboard.twig.appname_extension:
            class: Kodoyosa\DashboardBundle\Twig\AppnameExtension
            arguments: ["@doctrine.orm.entity_manager"]
            tags:
                - { name: twig.extension }
