general_index:
    path:     /
    defaults: { _controller: "KodoyosaDashboardBundle:General:index" }
    methods:  GET

general_show:
    path:     /{id}/show
    defaults: { _controller: "KodoyosaDashboardBundle:General:show" }
    methods:  GET

general_new:
    path:     /new
    defaults: { _controller: "KodoyosaDashboardBundle:General:new" }
    methods:  [GET, POST]

general_edit:
    path:     /{id}/edit
    defaults: { _controller: "KodoyosaDashboardBundle:General:edit" }
    methods:  [GET, POST]

general_delete:
    path:     /{id}/delete
    defaults: { _controller: "KodoyosaDashboardBundle:General:delete" }
    methods:  DELETE
