itemmenu_index:
    path:     /
    defaults: { _controller: "KodoyosaDashboardBundle:Itemmenu:index" }
    methods:  GET

itemmenu_show:
    path:     /{id}/show
    defaults: { _controller: "KodoyosaDashboardBundle:Itemmenu:show" }
    methods:  GET

itemmenu_new:
    path:     /new
    defaults: { _controller: "KodoyosaDashboardBundle:Itemmenu:new" }
    methods:  [GET, POST]

itemmenu_edit:
    path:     /{id}/edit
    defaults: { _controller: "KodoyosaDashboardBundle:Itemmenu:edit" }
    methods:  [GET, POST]

itemmenu_delete:
    path:     /{id}/delete
    defaults: { _controller: "KodoyosaDashboardBundle:Itemmenu:delete" }
    methods:  DELETE
